---
title: "data_visualization"
author: "Sandy De Groote"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, waring =F}
library(dplyr)
library(tidyr)
library(ggplot2)
library(leaflet)
library(scales)
library(DT)
```

# Prepare data

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        write.csv(esc, "data/escapement.csv", row.names = F)
        return(esc)
    }
)
head(esc)
```

Annual escapement by Species, Region, Year
    *only for Sockeye, Chinook, Coho, Pink, Chum
 
```{r}
annual_esc <- esc %>% 
    
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum"))
  # %in%   is like using "or"   

head(annual_esc)
```
 
# create static plots

```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = escapement)) +
    geom_col(fill="blue")

```

```{r}
ggplot(annual_esc, mapping = aes(x =Species, y = escapement, fill = SASAP.Region)) +
    geom_col()
```

```{r}
annual_esc %>%
    filter(SASAP.Region == "Kodiak") %>% 
    ggplot (mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line() +
    geom_point()
```

```{r}
kodiak_esc <- annual_esc %>% 
    filter(SASAP.Region == "Kodiak")

ggplot(kodiak_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line() +
    geom_point() +
    ylab("Escapement (num. fish)") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
```

```{r}
kodiak_esc <- annual_esc %>% 
    filter(SASAP.Region == "Kodiak")

ggplot(kodiak_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
#  scale_y_continuous(labels = comma)  puts labels on the side
    ylab("Escapement (num. fish)") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
```

```{r}
kodiak_esc <- annual_esc %>% 
    filter(SASAP.Region == "Kodiak")

ggplot(kodiak_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
#  scale_y_continuous(labels = comma)  puts labels on the side
    ylab("Escapement (num. fish)") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
    theme(legend.position = "bottom")
```
```{r}
kodiak_esc <- annual_esc %>% 
    filter(SASAP.Region == "Kodiak")

my_theme <-theme_bw() +
    theme(legend.position = "bottom")

pal <- c("blue", "green", "kahki", "gray", "yellow")
# use the above to create a theme to use throughout without repeating theme code

ggplot(kodiak_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
#  scale_y_continuous(labels = comma)  puts labels on the side
    ylab("Escapement (num. fish)") +
    ggtitle("Kodiak Salmon Escapement") +
        my_theme

```

```{r}
ggplot(annual_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
    geom_line()+
    geom_point()+
    facet_wrap(~SASAP.Region, ncol = 3, scales = "free_y") +
    # could also use "free"   or "free_x)
    scale_y_continuous(labels = comma) +
    ylab("Escapement (num. fish)")+
    my_theme

ggsave("figure.png", height = 7, width = 7, units = "in", dpi = 300)
# to create a figure
```

```{r}
locations <- esc %>% 
    distinct(Location, Latitude, Longitude) %>% 
    drop_na()
locations
```

```{r}
datatable(locations)
```
```{r}
datatable(locations)
```


#Create an interactive table


#create an interactive map

```{r}
leaflet(locations) %>%  
    addTiles() %>% 
    addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location)
```

```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```
```{r}

```


